version: "3.8"

services:
  bot:
    image: ghcr.io/fyysikkokilta/fiisubot:latest
    restart: always
    env_file:
      - .env

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
